version: "3"

services:
    
    php:
        image: vulture20/7.4-fpm
        container_name: ${APP_NAME}_php
        ports:
            - "9000"
#        user: www-data:www-data
        volumes:
            - ./:/var/www/html/my-blog
            
    nginx:
        image: nginx:1.19
        container_name: ${APP_NAME}_nginx
        volumes:
            - ./docker/nginx:/etc/nginx/templates
            - ./:/var/www/html/my-blog
        ports:
            - "80:80"
        environment:
            - NGINX_HOST=localhost.com
            - NGINX_PORT=80
        depends_on:
            - php