version: "3"

services:

    php:
      image: vulture20/7.4-fpm
      container_name: ${APP_NAME}_php
      ports:
          - "9000"
      volumes:
          - ./:/var/www/html/my-blog

    nginx:
      image: nginx:1.19
      container_name: ${APP_NAME}_nginx
      volumes:
          - ./docker/nginx:/etc/nginx/templates
          - ./:/var/www/html/my-blog
      ports:
          - "80:80"
      environment:
          - NGINX_HOST=localhost.com
          - NGINX_PORT=80
      depends_on:
          - php

    mysql:
      image: mysql:5.7
      container_name: ${APP_NAME}_mysql
      volumes:
        - ./docker/mysql/logs:/var/log/mysql
        - ./docker/mysql/data:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: '${DB_PASSWORD_ROOT}'
        MYSQL_DATABASE: '${DB_DATABASE}'
        MYSQL_USER: '${DB_USERNAME}'
        MYSQL_PASSWORD: '${DB_PASSWORD}'
      ports:
        - '${DB_PORT}:3306'
      depends_on:
        - php
